# More option see https://github.com/Eric-Guo/wechat#menu-create
button:
 -
  type: "view"
  name: "中介搜索"
  url:  "http://ehero.cc"
 -
  type: "view"
  name: "免扰电话"
  url:  "http://ehero.cc/helper"
 -
  name: "其他功能"
  sub_button:
   -
    type: "view"
    name: "锦囊"
    url:  "http://ehero.cc/tips"
   -
    type: "click"
    name: "微信群"
    key:  "GROUPS"
   -
    type: "click"
    name: "评价"
    key:  "COMMENT"
   -
    type: "view"
    name: "帮助"
    url:  "http://ehero.cc/site/faq"
   -
    type: "view"
    name: "关于我们"
    url:  "http://ehero.cc/site/aboutus"
